spring:
  application:
    name: account-microservice
    
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
       
server:
  port: 2001
  
error:
  whitelabel:
    enabled: false
   